name: ipdk-plugin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: makefile-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create tags and labels
      id: image_meta
      uses: docker/metadata-action@v3
      with:
        sep-tags: ","
        sep-labels: ","
        # list of names to use as base name for tags
        # add for dockerhub: ipdk-io/ipdk-${{ matrix.os }}-${{ steps.system.outputs.arch }}
        images: |
          ghcr.io/${{ github.repository_owner }}/ipdk-plugin
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: ipdk-plugin image build and push
      if: github.event_name != 'pull_request'
      run: |
        TAGS=${{ steps.image_meta.outputs.tags }} make github-docker-merge

    - name: ipdk-plugin image build and export
      if: github.event_name == 'pull_request'
      run: |
        TAGS=${{ steps.image_meta.outputs.tags }} TAR_EXPORT=/tmp/ipdk-plugin.tar make github-docker-pull-request

    - name: Upload build artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v2
      with:
        name: ipdk-plugin
        path: /tmp/ipdk-plugin.tar
        retention-days: 1
